import React, { useState, useRef } from "react";
import { ToolDefinition } from "@/types/tool";
import { ToolShell } from "@/components/common/ToolShell";
import { downloadDataUrl } from "@/lib/download";
import {
  Upload,
  Camera,
  Grid,
  Download,
  RotateCcw,
  Sparkles,
} from "lucide-react";

interface FrameExtractorProps {
  tool: ToolDefinition;
}

export const FrameExtractor: React.FC<FrameExtractorProps> = ({ tool }) => {
  const [videoFile, setVideoFile] = useState<File | null>(null);
  const [videoUrl, setVideoUrl] = useState<string | null>(null);
  const [duration, setDuration] = useState(0);

  const [mode, setMode] = useState<"single" | "contact">("single");
  const [timestamp, setTimestamp] = useState(0);
  const [capturedStill, setCapturedStill] = useState<string | null>(null);

  // Contact sheet settings
  const [gridSize, setGridSize] = useState<3 | 4 | 5>(3);
  const [contactSheetUrl, setContactSheetUrl] = useState<string | null>(null);
  const [generatingSheet, setGeneratingSheet] = useState(false);
  const [sheetProgress, setSheetProgress] = useState(0);

  const videoRef = useRef<HTMLVideoElement>(null);

  const handleFile = (file: File) => {
    const url = URL.createObjectURL(file);
    setVideoFile(file);
    setVideoUrl(url);
    setCapturedStill(null);
    setContactSheetUrl(null);
  };

  const handleLoadedMetadata = () => {
    if (videoRef.current) {
      setDuration(videoRef.current.duration);
      setTimestamp(0);
    }
  };

  const captureSingleFrame = () => {
    const video = videoRef.current;
    if (!video) return;

    const canvas = document.createElement("canvas");
    canvas.width = video.videoWidth;
    canvas.height = video.videoHeight;
    const ctx = canvas.getContext("2d");
    if (!ctx) return;

    ctx.drawImage(video, 0, 0, canvas.width, canvas.height);
    const dataUrl = canvas.toDataURL("image/png");
    setCapturedStill(dataUrl);
  };

  const generateContactSheet = async () => {
    const video = videoRef.current;
    if (!video || !duration) return;

    setGeneratingSheet(true);
    setSheetProgress(0);

    const cols = gridSize;
    const rows = gridSize;
    const totalFrames = cols * rows;

    const thumbW = 360;
    const thumbH = Math.round(thumbW * (video.videoHeight / video.videoWidth));
    const padding = 12;
    const headerH = 60;

    const canvasW = cols * thumbW + (cols + 1) * padding;
    const canvasH = headerH + rows * thumbH + (rows + 1) * padding;

    const canvas = document.createElement("canvas");
    canvas.width = canvasW;
    canvas.height = canvasH;
    const ctx = canvas.getContext("2d");
    if (!ctx) {
      setGeneratingSheet(false);
      return;
    }

    // Background
    ctx.fillStyle = "#18181b";
    ctx.fillRect(0, 0, canvasW, canvasH);

    // Header
    ctx.fillStyle = "#f4f4f5";
    ctx.font = "bold 16px sans-serif";
    ctx.fillText(`${videoFile?.name || "Video"}`, padding, 26);
    ctx.fillStyle = "#a1a1aa";
    ctx.font = "12px monospace";
    ctx.fillText(
      `Resolution: ${video.videoWidth}x${video.videoHeight} • Duration: ${duration.toFixed(1)}s • Generated by Eureka Dev Tools`,
      padding,
      46,
    );

    const interval = duration / (totalFrames + 1);

    for (let i = 0; i < totalFrames; i++) {
      const time = interval * (i + 1);

      await new Promise<void>((resolve) => {
        const onSeeked = () => {
          video.removeEventListener("seeked", onSeeked);
          resolve();
        };
        video.addEventListener("seeked", onSeeked);
        video.currentTime = time;
      });

      const col = i % cols;
      const row = Math.floor(i / cols);
      const x = padding + col * (thumbW + padding);
      const y = headerH + padding + row * (thumbH + padding);

      ctx.drawImage(video, x, y, thumbW, thumbH);

      // Timestamp tag
      ctx.fillStyle = "rgba(0, 0, 0, 0.75)";
      ctx.fillRect(x + thumbW - 65, y + thumbH - 24, 60, 20);
      ctx.fillStyle = "#34d399";
      ctx.font = "11px monospace";
      ctx.fillText(`${time.toFixed(1)}s`, x + thumbW - 55, y + thumbH - 10);

      setSheetProgress(Math.round(((i + 1) / totalFrames) * 100));
    }

    const sheetDataUrl = canvas.toDataURL("image/jpeg", 0.88);
    setContactSheetUrl(sheetDataUrl);
    setGeneratingSheet(false);
  };

  return (
    <ToolShell tool={tool}>
      <div className="space-y-6">
        {!videoUrl ? (
          <div
            onDragOver={(e) => e.preventDefault()}
            onDrop={(e) => {
              e.preventDefault();
              const f = e.dataTransfer.files[0];
              if (f) handleFile(f);
            }}
            className="border-2 border-dashed border-zinc-700 hover:border-emerald-500/50 rounded-2xl p-12 text-center transition-all bg-zinc-900/40"
          >
            <div className="w-16 h-16 mx-auto rounded-2xl bg-zinc-800 flex items-center justify-center mb-4 text-emerald-400">
              <Camera className="w-8 h-8" />
            </div>
            <h3 className="text-lg font-medium text-zinc-200 mb-1">
              Select Video to Extract Frames
            </h3>
            <p className="text-sm text-zinc-400 mb-6">
              Capture full-resolution frame stills or generate contact sheets.
            </p>
            <label className="inline-flex items-center gap-2 px-5 py-2.5 rounded-xl bg-emerald-600 hover:bg-emerald-500 text-white font-medium cursor-pointer transition">
              <Upload className="w-4 h-4" />
              <span>Choose Video</span>
              <input
                type="file"
                accept="video/*"
                className="hidden"
                onChange={(e) => {
                  const f = e.target.files?.[0];
                  if (f) handleFile(f);
                }}
              />
            </label>
          </div>
        ) : (
          <div className="space-y-6">
            {/* Mode Switcher */}
            <div className="flex rounded-xl bg-zinc-900 p-1 border border-zinc-800 w-fit">
              <button
                onClick={() => setMode("single")}
                className={`flex items-center gap-2 px-4 py-2 rounded-lg text-xs font-medium transition ${
                  mode === "single" ? "bg-emerald-600 text-white" : "text-zinc-400 hover:text-zinc-200"
                }`}
              >
                <Camera className="w-4 h-4" />
                <span>Single Frame Grabber</span>
              </button>
              <button
                onClick={() => setMode("contact")}
                className={`flex items-center gap-2 px-4 py-2 rounded-lg text-xs font-medium transition ${
                  mode === "contact" ? "bg-emerald-600 text-white" : "text-zinc-400 hover:text-zinc-200"
                }`}
              >
                <Grid className="w-4 h-4" />
                <span>Contact Sheet Generator</span>
              </button>
            </div>

            {/* Video Player */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div className="p-5 rounded-2xl bg-zinc-900 border border-zinc-800 space-y-3">
                <h4 className="text-xs font-medium text-zinc-400">Video Player & Seeker</h4>
                <div className="aspect-video bg-zinc-950 rounded-xl overflow-hidden border border-zinc-800 flex items-center justify-center">
                  <video
                    ref={videoRef}
                    src={videoUrl}
                    onLoadedMetadata={handleLoadedMetadata}
                    controls
                    className="w-full h-full object-contain"
                  />
                </div>
                {mode === "single" && (
                  <div className="space-y-2 pt-2">
                    <label className="text-xs font-medium text-zinc-400 flex items-center justify-between">
                      <span>Seek Timestamp</span>
                      <span className="font-mono text-emerald-400">{timestamp.toFixed(2)}s</span>
                    </label>
                    <input
                      type="range"
                      min="0"
                      max={duration}
                      step="0.05"
                      value={timestamp}
                      onChange={(e) => {
                        const val = Number(e.target.value);
                        setTimestamp(val);
                        if (videoRef.current) videoRef.current.currentTime = val;
                      }}
                      className="w-full accent-emerald-500"
                    />
                    <button
                      onClick={captureSingleFrame}
                      className="flex items-center gap-2 px-4 py-2 rounded-xl bg-emerald-600 hover:bg-emerald-500 text-white text-xs font-medium transition"
                    >
                      <Camera className="w-4 h-4" />
                      <span>Capture Frame at Current Time</span>
                    </button>
                  </div>
                )}
              </div>

              {/* Output Preview */}
              <div className="p-5 rounded-2xl bg-zinc-900 border border-zinc-800 space-y-3">
                <h4 className="text-xs font-medium text-zinc-400">
                  {mode === "single" ? "Captured Frame" : "Generated Contact Sheet"}
                </h4>
                <div className="aspect-video bg-zinc-950 rounded-xl overflow-hidden border border-zinc-800 flex items-center justify-center">
                  {mode === "single" ? (
                    capturedStill ? (
                      <img src={capturedStill} alt="Captured frame" className="max-h-full max-w-full object-contain" />
                    ) : (
                      <p className="text-xs text-zinc-600">No frame captured yet.</p>
                    )
                  ) : contactSheetUrl ? (
                    <img src={contactSheetUrl} alt="Contact sheet" className="max-h-full max-w-full object-contain" />
                  ) : (
                    <p className="text-xs text-zinc-600">
                      {generatingSheet ? `Rendering frames... ${sheetProgress}%` : "Click Generate below."}
                    </p>
                  )}
                </div>

                {mode === "single" && capturedStill && (
                  <button
                    onClick={() => downloadDataUrl(capturedStill, `${videoFile?.name || "frame"}-still.png`)}
                    className="flex items-center gap-2 px-4 py-2 rounded-xl bg-emerald-600 hover:bg-emerald-500 text-white text-xs font-medium transition"
                  >
                    <Download className="w-4 h-4" />
                    <span>Download PNG Still</span>
                  </button>
                )}

                {mode === "contact" && (
                  <div className="space-y-3 pt-2">
                    <div className="flex items-center gap-3">
                      <label className="text-xs font-medium text-zinc-400">Grid Format:</label>
                      {[3, 4, 5].map((g) => (
                        <button
                          key={g}
                          onClick={() => setGridSize(g as 3 | 4 | 5)}
                          className={`px-3 py-1 rounded-lg text-xs font-medium transition ${
                            gridSize === g ? "bg-emerald-600 text-white" : "bg-zinc-800 text-zinc-400"
                          }`}
                        >
                          {g}×{g} ({g * g} stills)
                        </button>
                      ))}
                    </div>

                    <div className="flex items-center gap-2">
                      <button
                        disabled={generatingSheet}
                        onClick={generateContactSheet}
                        className="flex items-center gap-2 px-5 py-2 rounded-xl bg-emerald-600 hover:bg-emerald-500 disabled:opacity-50 text-white text-xs font-medium transition"
                      >
                        <Sparkles className="w-4 h-4" />
                        <span>{generatingSheet ? `Generating (${sheetProgress}%)` : "Generate Contact Sheet"}</span>
                      </button>
                      {contactSheetUrl && (
                        <button
                          onClick={() => downloadDataUrl(contactSheetUrl, `${videoFile?.name || "video"}-contact-sheet.jpg`)}
                          className="flex items-center gap-1.5 px-4 py-2 rounded-xl bg-zinc-800 hover:bg-zinc-700 text-zinc-200 text-xs font-medium transition border border-zinc-700"
                        >
                          <Download className="w-4 h-4" />
                          <span>Download JPEG</span>
                        </button>
                      )}
                    </div>
                  </div>
                )}
              </div>
            </div>

            <div className="flex justify-end">
              <label className="flex items-center gap-1.5 px-3 py-2 rounded-xl bg-zinc-800 hover:bg-zinc-700 text-zinc-400 hover:text-zinc-200 text-xs font-medium cursor-pointer transition">
                <RotateCcw className="w-3.5 h-3.5" />
                <span>Change Video</span>
                <input
                  type="file"
                  accept="video/*"
                  className="hidden"
                  onChange={(e) => {
                    const f = e.target.files?.[0];
                    if (f) handleFile(f);
                  }}
                />
              </label>
            </div>
          </div>
        )}
      </div>
    </ToolShell>
  );
};

export default FrameExtractor;
